BaseURL = "http://arresteddevops.github.io/"
languageCode = "en-us"
title = "Arrested DevOps"
theme = "ado"

[permalinks]
	page = "/:title/"
	about = "/:filename/"

[params]
Facebook = "//facebook.com/Arresteddevops"
GATracker = ""
Twitter = "//twitter.com/arresteddevops"
