baseurl = "http://arresteddevops.github.io/"
# baseurl = "http://localhost:1313/"
languageCode = "en-us"
title = "Arrested DevOps"
theme = "ado"

[permalinks]
	page = "/:title/"
	about = "/:filename/"
