BaseURL = "http://arresteddevops.github.io/"
languageCode = "en-us"
title = "Arrested DevOps"
theme = "ado"
canonifyurls = true
dataDir = "data"
disqusShortname = "arresteddevops"

[permalinks]
	page = "/:title/"
	about = "/:filename/"
	episode = "/:filename/"

[params]
Facebook = "//facebook.com/Arresteddevops"
GATracker = ""
Twitter = "//twitter.com/arresteddevops"
